name: live-chat-dev

services:
  db:
    image: postgres:16-alpine
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: ${PSQL_USER:-postgres}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD:-postgres}
      POSTGRES_DB: ${PSQL_DATABASE:-live_chat}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  db-test:
    image: postgres:16-alpine
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: ${PSQL_USER:-postgres}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD:-postgres}
      POSTGRES_DB: live_chat_test
    volumes:
      - db_test_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redis-test:
    image: redis:7-alpine
    ports:
      - '6381:6379'
    volumes:
      - redis_test_data:/data
    restart: unless-stopped

volumes:
  db_data:
  db_test_data:
  redis_data:
  redis_test_data: